services:
  - type: web
    name: cosmic-vibes-backend
    env: docker
    rootDirectory: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: FRONTEND_ORIGIN
        value: https://duamp3.vercel.app
